name: shaped_widget_package
description: A collection of customizable Flutter widgets for drawing shapes such as dots, triangle and star.
version: 1.1.0
homepage: https://github.com/nashxHein2003/shaped-widget
license: MIT

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  integration_test:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
